2021-05-04 19:55:55,538 INFO    MainThread:40428 [wandb_setup.py:_flush():69] setting env: {}
2021-05-04 19:55:55,538 INFO    MainThread:40428 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-04 19:55:55,539 INFO    MainThread:40428 [wandb_init.py:_log_setup():336] Logging user logs to C:\Users\User\Documents\CS182\Project\CS182RLProject\wandb\run-20210504_195555-1dxr6clx\logs\debug.log
2021-05-04 19:55:55,539 INFO    MainThread:40428 [wandb_init.py:_log_setup():337] Logging internal logs to C:\Users\User\Documents\CS182\Project\CS182RLProject\wandb\run-20210504_195555-1dxr6clx\logs\debug-internal.log
2021-05-04 19:55:55,539 INFO    MainThread:40428 [wandb_init.py:init():369] calling init triggers
2021-05-04 19:55:55,540 INFO    MainThread:40428 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-05-04 19:55:55,540 INFO    MainThread:40428 [wandb_init.py:init():418] starting backend
2021-05-04 19:55:55,540 INFO    MainThread:40428 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-05-04 19:55:55,547 INFO    MainThread:40428 [backend.py:ensure_launched():123] starting backend process...
2021-05-04 19:55:55,629 INFO    MainThread:40428 [backend.py:ensure_launched():128] started backend process with pid: 23376
2021-05-04 19:55:55,630 INFO    MainThread:40428 [wandb_init.py:init():423] backend started and connected
2021-05-04 19:55:55,633 INFO    MainThread:40428 [wandb_init.py:init():465] updated telemetry
2021-05-04 19:55:55,633 INFO    MainThread:40428 [wandb_init.py:init():484] communicating current version
2021-05-04 19:55:56,723 INFO    MainThread:40428 [wandb_init.py:init():489] got version response 
2021-05-04 19:55:56,723 INFO    MainThread:40428 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-04 19:56:26,732 INFO    MainThread:40428 [interface.py:_communicate_run():649] couldn't get run from backend
2021-05-04 19:56:26,732 ERROR   MainThread:40428 [wandb_init.py:init():501] backend process timed out
2021-05-04 19:56:26,732 ERROR   MainThread:40428 [wandb_init.py:init():510] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-05-04 19:56:26,747 ERROR   MainThread:40428 [wandb_init.py:init():770] error
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\cs182-project\lib\site-packages\wandb\sdk\wandb_init.py", line 744, in init
    run = wi.init()
  File "C:\Users\User\anaconda3\envs\cs182-project\lib\site-packages\wandb\sdk\wandb_init.py", line 513, in init
    backend.cleanup()
  File "C:\Users\User\anaconda3\envs\cs182-project\lib\site-packages\wandb\sdk\backend\backend.py", line 154, in cleanup
    self.interface.join()
  File "C:\Users\User\anaconda3\envs\cs182-project\lib\site-packages\wandb\sdk\interface\interface.py", line 828, in join
    _ = self._communicate(record)
  File "C:\Users\User\anaconda3\envs\cs182-project\lib\site-packages\wandb\sdk\interface\interface.py", line 537, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\User\anaconda3\envs\cs182-project\lib\site-packages\wandb\sdk\interface\interface.py", line 542, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
